// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhvtqfvdwqiulxsdkflr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhodnRxZnZkd3FpdWx4c2RrZmxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTUyNjUsImV4cCI6MjA2MjQ3MTI2NX0.E8HquvZSnOiM_ZlonM_1jAW4Q7WohE4_Rvo4_1rbmzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);